name: 'Minify GitHub Pages'
description: 'Minify js, css, and html files for GitHub pages before publishing'
author: 'Massi-X'

inputs:
  source:
    description: 'Directory where the source files reside. This should be the dir where jekyll outputs to.'
    required: false
    default: ./_site/
  compress:
    description: 'Which files to compress. Choose between js, css and html or a combination of them, comma separated.'
    required: false
    default: js,css,html
  js_options:
    description: 'JS compressor options. See https://github.com/mishoo/UglifyJS for the full list.'
    required: false
    default: '{"mangle": false}'
  css_options:
    description: 'CSS compressor options. See https://github.com/clean-css/clean-css for the full list.'
    required: false
    default: '{}'
  html_options:
    description: 'HTML compressor options. See https://github.com/kangax/html-minifier for the full list.'
    required: false
    default: '{"collapseInlineTagWhitespace": false}'
  
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: "trending-down"
  color: "gray-dark"
